### PR TITLE
Hypertrace Release 0.6.40-0.1.0

### PR DESCRIPTION
**Pull request by suddendust**

### CODE REVIEW

**Comment by TriptiTripathi1234** [comment]
Why is this file(CHANGELOG.md) empty?is this a mock PR?

**Comment by suddendust** [comment]
@TriptiTripathi1234 It's to trigger the PR, else there would have been no diff. I didn't put in any changelog as that would anyway go the release notes.

**Review by TriptiTripathi1234 — APPROVED** [review]
LGTM

**Pull request merged**
